### ISSUE TITLE
"Start Offset" on "Spline Animate" is HEAVY bugged. Pls fix. (2.2.1)

### ISSUE THREAD

**Issue by Sovereing2027** [needle-mirror/com.unity.splines#1]

**Comment by marwie** [comment]
Hi, please report bugs to Unity directly. This is just a mirror and it wont reach the spline devs here unfortunately

**Comment by Sovereing2027** [comment]
> Hi, please report bugs to Unity directly. This is just a mirror and it wont reach the spline devs here unfortunately

Thx for feedback.
Where can i do this? (Sorry for the noob question... Anyways.)

**Comment by marwie** [comment]
https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-
