### ISSUE TITLE
Unity still provides 2.2.1 instead of 2.3.0

### ISSUE THREAD

**Issue by Sovereing2027** [needle-mirror/com.unity.splines#2]
I found this asset very useful, but "start offset" bug at 2.2.1 is soo frustrating
My unity version is 2022.3.2f1
![изображение](https://github.com/needle-mirror/com.unity.splines/assets/138771312/2ae4c4e5-9388-40ba-9e08-4c03302a6ac5)

**Comment by Sovereing2027** [comment]
Can you help me (a unity noob) pls? :D

**Comment by marwie** [comment]
Hi, please report bugs to Unity directly. This is just a mirror and it wont reach the spline devs here unfortunately
